spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/chronos_kanban}
spring.datasource.username=${DB_USERNAME:chronos}
spring.datasource.password=${DB_PASSWORD:chronos}

spring.jpa.hibernate.ddl-auto=validate